/** @deprecated import from `@/services/studyService.js` — thin re-export of `src/services/study/` */
export {
  StudyApiError,
  getCurriculum,
  buildRoadmapStage,
  getLearningRoadmap,
  pickStageLearningItems,
  getLearningProgress,
  getSubChapterContent,
  getLessonPages,
  saveLessonProgress,
  mapQuizAttemptQuestion,
  mapQuizAttemptStart,
  mapQuizAnswerGrading,
  startSubChapterQuizAttempt,
  startMainChapterQuizAttempt,
  gradeQuizAttemptAnswer,
  getQuizQuestions,
  submitQuizAttempt,
  getChapterGame,
  getScenario,
  submitScenarioAttempt,
  getContinuePosition,
  __setMockLearningProfile,
  __getMockLearningProfile,
} from './study/index.js'
