/** @deprecated import from `@/services/studyService.js` — thin re-export of `src/services/study/` */
export {
  StudyApiError,
  getCurriculum,
  buildRoadmapStage,
  getLearningRoadmap,
  pickStageLearningItems,
  getLearningProgress,
  mergeLearningItemsWithProgress,
  getSubChapterContent,
  getLessonPages,
  saveLessonProgress,
  mapQuizAttemptQuestion,
  mapQuizAttemptStart,
  mapQuizAnswerGrading,
  startSubChapterQuizAttempt,
  startMainChapterQuizAttempt,
  gradeQuizAttemptAnswer,
  getContinuePosition,
} from './study/index.js'
